### ISSUE TITLE
get error FormatException while doing pre() or next(). 

### ISSUE THREAD

**Issue by yashwant1999** [anhoder/mp3_player#1]
1. I get the Following Error While going throw previous and backward :-  
`next
Unhandled exception:
FormatException: Bad UTF-8 encoding 0x84 (at offset 16)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:532:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#9      _StreamController._add (dart:async/stream_controller.dart:655:7)
#10     _StreamController.add (dart:async/stream_controller.dart:597:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#16     _StreamController._add (dart:async/stream_controller.dart:655:7)
#17     _StreamController.add (dart:async/stream_controller.dart:597:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
process is terminated with return code 255.`

**Comment by anhoder** [comment]
😀Hi, can you provide information about **the running environment** and some **related code**?

**Comment by yashwant1999** [comment]
> Hi, can you provide information about **the running environment** and some **related code**?

Well issue happend to be with  one of my **mp3 file**....Since when i played your sample song it worked fine.

Although what can go wrong with one mp3 file.?? Since it played well via terminal by **mpg123**.

**Running enviroment**:- Linux , Ubuntu Mate 20.0.
And code was yours example  only with  change of mp3 file .

**Comment by anhoder** [comment]
Sorry, I can't get your exception using my mp3 files, and they worked fine. Can you send your mp3 file to my email? thx.
> My email is alan1766447919@gmail.com

**Comment by anhoder** [comment]
> > Hi, can you provide information about **the running environment** and some **related code**?
> 
> Well issue happend to be with one of my **mp3 file**....Since when i played your sample song it worked fine.
> 
> Although what can go wrong with one mp3 file.?? Since it played well via terminal by **mpg123**.
> 
> **Running enviroment**:- Linux , Ubuntu Mate 20.0.
> And code was yours example only with change of mp3 file .

Hello, I released a new version(`0.1.2`) to fix this issue. 
Also, I put the mp3 file you provided in the `example` folder and named it `b.mp3`. 
You can run it again with the new version.

**Comment by yashwant1999** [comment]
Thank you for your response....and fixing problem..🤟😊
